### ISSUE TITLE
Logo rpi-virtuell ersetzen

### ISSUE THREAD

**Issue by joerglohrer** [programmieraffe/oer-hoernchen#4]
aktuell ist dieses:
https://about.rpi-virtuell.de/wp-content/uploads/2017/05/splash-1-1600x800.jpg

**Comment by mandrasch** [comment]
Erledigt, danke! :-)

https://github.com/programmieraffe/oer-hoernchen/commit/7ce5a20f9996eb6eeca6087f6b2b1b4be5a3b829
