### ISSUE TITLE
Google Suche rpi-virtuell.net aktualisieren

### ISSUE THREAD

**Issue by joerglohrer** [programmieraffe/oer-hoernchen#5]
![image](https://user-images.githubusercontent.com/1091954/33982886-8cbfe68c-e0b2-11e7-9175-e90670666b99.png)
rpi-virtuell.net war unsere alte Seite - Neu ist https://rpi-virtuell.de
Allerdings ist Material vorwiegend auf https://material.rpi-virtuell.de/ zu finden.
Alternativ zur Google-Such kann auch die Wordpress-API genutzt werden um die Suchergebnisse via json zu empfangen

**Comment by mandrasch** [comment]
Erledigt, danke! :-)

https://github.com/programmieraffe/oer-hoernchen/commit/3bf9eb7bca983fbbb494014e6ee24eb16583d3a3

**Comment by mandrasch** [comment]
Danke auch für die Anmerkung bzgl. der Wordpress-API. Derzeit ist das OERhörnchen so simpel wie möglich gehalten und nutzt die Serverkraft von Google. Über Nutzung von APIs könnte ich aber 2018 mal nachdenken, vielleicht gibt es da zielführende Implementierungsmöglichkeiten  :-)
